// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/change-password": {
            "post": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "Employee Change Password",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SA - Auth"
                ],
                "summary": "Employee Change Password",
                "parameters": [
                    {
                        "description": "Change password Request",
                        "name": "_",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.ChangePasswordRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/basemodel.ApiEmptyResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/basemodel.ApiError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/basemodel.ApiError"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/basemodel.ApiError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/basemodel.ApiError"
                        }
                    }
                }
            }
        },
        "/auth/create-employee": {
            "post": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "Create Employee",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SA - Employee"
                ],
                "summary": "Create Employee",
                "parameters": [
                    {
                        "description": "CreateEmployeeRequest Request",
                        "name": "_",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.CreateEmployeeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/basemodel.ApiEmptyResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/basemodel.ApiError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/basemodel.ApiError"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/basemodel.ApiError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/basemodel.ApiError"
                        }
                    }
                }
            }
        },
        "/auth/department/create-department": {
            "post": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "Create Department",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SA - Department"
                ],
                "summary": "Create Department",
                "parameters": [
                    {
                        "description": "CreateDepartmentRequest Request",
                        "name": "_",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.CreateDepartmentRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/basemodel.ApiEmptyResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/basemodel.ApiError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/basemodel.ApiError"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/basemodel.ApiError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/basemodel.ApiError"
                        }
                    }
                }
            }
        },
        "/auth/department/list-department": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "List Department",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SA - Department"
                ],
                "summary": "List Department",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page size",
                        "name": "size",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "name",
                            "code"
                        ],
                        "type": "string",
                        "description": "Sort field. Default to name,asc",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Ignore pagination and return all data",
                        "name": "paging_ignored",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Search by name",
                        "name": "search",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/authmodel.ListDepartment"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/basemodel.ApiError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/basemodel.ApiError"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/basemodel.ApiError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/basemodel.ApiError"
                        }
                    }
                }
            }
        },
        "/auth/list-employee": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "List Employee",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SA - Employee"
                ],
                "summary": "List Employee",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page size",
                        "name": "size",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "name",
                            "code"
                        ],
                        "type": "string",
                        "description": "Sort field. Default to code,asc",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Ignore pagination and return all data",
                        "name": "paging_ignored",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by department id",
                        "name": "department_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Search by name or email, code, phone number",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by employee id",
                        "name": "employee_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Filter by employee type 1: Doctor, 2: Nurse",
                        "name": "employee_type",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/authmodel.ListEmployee"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/basemodel.ApiError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/basemodel.ApiError"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/basemodel.ApiError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/basemodel.ApiError"
                        }
                    }
                }
            }
        },
        "/auth/login": {
            "post": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "Employee Login",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SA - Auth"
                ],
                "summary": "Employee Login",
                "parameters": [
                    {
                        "description": "Login Request",
                        "name": "_",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/authmodel.LoginResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/basemodel.ApiError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/basemodel.ApiError"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/basemodel.ApiError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/basemodel.ApiError"
                        }
                    }
                }
            }
        },
        "/auth/pre-flight": {
            "post": {
                "description": "Pre-flight Login",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SA - Auth"
                ],
                "summary": "Pre-flight Login",
                "parameters": [
                    {
                        "description": "Request body",
                        "name": "_",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/authmodel.GenerateLoginSecretRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/authmodel.GenerateLoginSecretResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/basemodel.ApiError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/basemodel.ApiError"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/basemodel.ApiError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/basemodel.ApiError"
                        }
                    }
                }
            }
        },
        "/patient/get-patient/{id}": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "Get Patient",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SA - Patient Management"
                ],
                "summary": "Get Patient",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Patient ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/patientmodel.GetPatientResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/basemodel.ApiError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/basemodel.ApiError"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/basemodel.ApiError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/basemodel.ApiError"
                        }
                    }
                }
            }
        },
        "/patient/list-patient": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "List Employee",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SA - Patient Management"
                ],
                "summary": "List Employee",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page size",
                        "name": "size",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "name"
                        ],
                        "type": "string",
                        "description": "Sort field. Default to name,asc",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Ignore pagination and return all data",
                        "name": "paging_ignored",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Search by name",
                        "name": "search",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/patientmodel.ListPatientResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/basemodel.ApiError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/basemodel.ApiError"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/basemodel.ApiError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/basemodel.ApiError"
                        }
                    }
                }
            }
        },
        "/patient/medical": {
            "post": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "Upsert Medical Record",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SA - Patient Management"
                ],
                "summary": "Upsert Medical Record",
                "parameters": [
                    {
                        "description": "Upsert medical record Request",
                        "name": "_",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/patient.UpsertMedicalRecordRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/basemodel.ApiEmptyResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/basemodel.ApiError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/basemodel.ApiError"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/basemodel.ApiError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/basemodel.ApiError"
                        }
                    }
                }
            }
        },
        "/patient/medical/history": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "Get Medical History",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SA - Patient Management"
                ],
                "summary": "Get Medical History",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page size",
                        "name": "size",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Ignore pagination and return all data",
                        "name": "paging_ignored",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Patient ID",
                        "name": "patient_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "From date",
                        "name": "from_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "To date",
                        "name": "to_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Created by, doctor ID or nurse ID",
                        "name": "created_by",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/patientmodel.GetMedicalHistoryResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/basemodel.ApiError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/basemodel.ApiError"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/basemodel.ApiError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/basemodel.ApiError"
                        }
                    }
                }
            }
        },
        "/patient/medical/history/{id}": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "Get Medical History Detail",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SA - Patient Management"
                ],
                "summary": "Get Medical History Detail",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Medical History ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/patientmodel.GetMedicalHistoryDetailResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/basemodel.ApiError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/basemodel.ApiError"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/basemodel.ApiError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/basemodel.ApiError"
                        }
                    }
                }
            }
        },
        "/patient/medical/prescription": {
            "post": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "Upsert Medical Prescription",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SA - Patient Management"
                ],
                "summary": "Upsert Medical Prescription",
                "parameters": [
                    {
                        "description": "Upsert medical prescription Request",
                        "name": "_",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/patient.UpsertMedicalPrescriptionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/basemodel.ApiEmptyResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/basemodel.ApiError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/basemodel.ApiError"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/basemodel.ApiError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/basemodel.ApiError"
                        }
                    }
                }
            }
        },
        "/patient/medical/surgery": {
            "post": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "Upsert Medical Surgery",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SA - Patient Management"
                ],
                "summary": "Upsert Medical Surgery",
                "parameters": [
                    {
                        "description": "Upsert medical surgery Request",
                        "name": "_",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/patient.UpsertMedicalSurgeryRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/basemodel.ApiEmptyResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/basemodel.ApiError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/basemodel.ApiError"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/basemodel.ApiError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/basemodel.ApiError"
                        }
                    }
                }
            }
        },
        "/patient/medical/treatment": {
            "post": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "Upsert Medical Treatment",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SA - Patient Management"
                ],
                "summary": "Upsert Medical Treatment",
                "parameters": [
                    {
                        "description": "Upsert medical treatment Request",
                        "name": "_",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/patient.UpsertMedicalTreatmentRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/basemodel.ApiEmptyResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/basemodel.ApiError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/basemodel.ApiError"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/basemodel.ApiError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/basemodel.ApiError"
                        }
                    }
                }
            }
        },
        "/patient/medication/list-medication": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "List Medication",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SA - Medication Management"
                ],
                "summary": "List Medication",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page size",
                        "name": "size",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "name",
                            "created_at"
                        ],
                        "type": "string",
                        "description": "Sort field. Default to name,asc",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Ignore pagination and return all data",
                        "name": "paging_ignored",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Search by name",
                        "name": "search",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/patientmodel.ListMedicationResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/basemodel.ApiError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/basemodel.ApiError"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/basemodel.ApiError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/basemodel.ApiError"
                        }
                    }
                }
            }
        },
        "/patient/medication/upsert-medication": {
            "post": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "Upsert Medication",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SA - Medication Management"
                ],
                "summary": "Upsert Medication",
                "parameters": [
                    {
                        "description": "Upsert medication Request",
                        "name": "_",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/patient.UpsertMedicationRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/basemodel.ApiEmptyResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/basemodel.ApiError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/basemodel.ApiError"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/basemodel.ApiError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/basemodel.ApiError"
                        }
                    }
                }
            }
        },
        "/patient/upsert-patient": {
            "post": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "Upsert Patient",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SA - Patient Management"
                ],
                "summary": "Upsert Patient",
                "parameters": [
                    {
                        "description": "Upsert patient Request",
                        "name": "_",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/patient.UpsertPatientRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/basemodel.ApiEmptyResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/basemodel.ApiError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/basemodel.ApiError"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/basemodel.ApiError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/basemodel.ApiError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "auth.ChangePasswordRequest": {
            "type": "object",
            "properties": {
                "new_password": {
                    "description": "encoded password",
                    "type": "string"
                },
                "old_password": {
                    "description": "encoded password",
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "auth.CreateDepartmentRequest": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                }
            }
        },
        "auth.CreateEmployeeRequest": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "date_of_birth": {
                    "type": "integer"
                },
                "degree_name": {
                    "type": "string"
                },
                "degree_year": {
                    "type": "integer"
                },
                "department_id": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "gender": {
                    "type": "integer"
                },
                "last_name": {
                    "type": "string"
                },
                "phone_number": {
                    "type": "string"
                },
                "start_date": {
                    "type": "integer"
                },
                "type": {
                    "type": "integer"
                }
            }
        },
        "auth.Department": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "auth.LoginRequest": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "auth.User": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "code": {
                    "type": "string"
                },
                "date_of_birth": {
                    "type": "integer"
                },
                "degree_name": {
                    "type": "string"
                },
                "degree_year": {
                    "type": "integer"
                },
                "department": {
                    "$ref": "#/definitions/auth.Department"
                },
                "end_date": {
                    "description": "Off board date",
                    "type": "integer"
                },
                "first_name": {
                    "type": "string"
                },
                "gender": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "phone_number": {
                    "type": "string"
                },
                "start_date": {
                    "description": "Onboard date",
                    "type": "integer"
                },
                "state": {
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "authmodel.Departments": {
            "type": "object",
            "properties": {
                "departments": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/auth.Department"
                    }
                },
                "hasNext": {
                    "type": "boolean"
                },
                "hasPrevious": {
                    "type": "boolean"
                },
                "page": {
                    "type": "integer"
                },
                "size": {
                    "type": "integer"
                },
                "totalElements": {
                    "description": "Num items in all pages",
                    "type": "integer"
                },
                "totalItems": {
                    "description": "Num items in current page",
                    "type": "integer"
                },
                "totalPages": {
                    "type": "integer"
                }
            }
        },
        "authmodel.Employees": {
            "type": "object",
            "properties": {
                "employees": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/auth.User"
                    }
                },
                "hasNext": {
                    "type": "boolean"
                },
                "hasPrevious": {
                    "type": "boolean"
                },
                "page": {
                    "type": "integer"
                },
                "size": {
                    "type": "integer"
                },
                "totalElements": {
                    "description": "Num items in all pages",
                    "type": "integer"
                },
                "totalItems": {
                    "description": "Num items in current page",
                    "type": "integer"
                },
                "totalPages": {
                    "type": "integer"
                }
            }
        },
        "authmodel.GenerateLoginSecretRequest": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "string"
                }
            }
        },
        "authmodel.GenerateLoginSecretResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "data": {
                    "$ref": "#/definitions/authmodel.LoginSecret"
                }
            }
        },
        "authmodel.ListDepartment": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "data": {
                    "$ref": "#/definitions/authmodel.Departments"
                }
            }
        },
        "authmodel.ListEmployee": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "data": {
                    "$ref": "#/definitions/authmodel.Employees"
                }
            }
        },
        "authmodel.LoginResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "next_step": {
                    "type": "integer"
                },
                "token": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/auth.User"
                }
            }
        },
        "authmodel.LoginSecret": {
            "type": "object",
            "properties": {
                "secret": {
                    "type": "string"
                }
            }
        },
        "basemodel.ApiEmptyResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "basemodel.ApiError": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "details": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/gcommon.ErrorDetail"
                    }
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "gcommon.ErrorDetail": {
            "type": "object",
            "properties": {
                "key": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "patient.MedicalHistory": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "integer"
                },
                "created_by": {
                    "$ref": "#/definitions/patient.User"
                },
                "diagnosis": {
                    "type": "string"
                },
                "doctor_notes": {
                    "type": "string"
                },
                "has_prescription": {
                    "type": "boolean"
                },
                "has_surgery": {
                    "type": "boolean"
                },
                "has_treatment": {
                    "type": "boolean"
                },
                "id": {
                    "type": "string"
                },
                "medical_end_date": {
                    "type": "integer"
                },
                "patient_id": {
                    "type": "string"
                },
                "reason": {
                    "type": "string"
                },
                "total_fee": {
                    "type": "number"
                },
                "updated_at": {
                    "type": "integer"
                },
                "updated_by": {
                    "$ref": "#/definitions/patient.User"
                }
            }
        },
        "patient.MedicalMedication": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "medication": {
                    "$ref": "#/definitions/patient.Medication"
                },
                "quantity": {
                    "type": "integer"
                }
            }
        },
        "patient.MedicalPrescription": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "integer"
                },
                "created_by": {
                    "$ref": "#/definitions/patient.User"
                },
                "fee": {
                    "type": "number"
                },
                "id": {
                    "type": "string"
                },
                "medical_history_id": {
                    "type": "string"
                },
                "medications": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/patient.MedicalMedication"
                    }
                },
                "prescription_date": {
                    "type": "integer"
                }
            }
        },
        "patient.MedicalSurgery": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "integer"
                },
                "created_by": {
                    "$ref": "#/definitions/patient.User"
                },
                "description": {
                    "type": "string"
                },
                "end_date": {
                    "type": "integer"
                },
                "fee": {
                    "type": "number"
                },
                "id": {
                    "type": "string"
                },
                "main_doctor_id": {
                    "type": "string"
                },
                "medical_history_id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "result": {
                    "type": "string"
                },
                "start_date": {
                    "type": "integer"
                },
                "support_doctor_ids": {
                    "description": "List of doctor ids, separated by comma",
                    "type": "string"
                },
                "support_nurse_ids": {
                    "description": "List of nurse ids, separated by comma",
                    "type": "string"
                },
                "updated_at": {
                    "type": "integer"
                },
                "updated_by": {
                    "$ref": "#/definitions/patient.User"
                }
            }
        },
        "patient.MedicalTreatment": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "integer"
                },
                "created_by": {
                    "$ref": "#/definitions/patient.User"
                },
                "description": {
                    "type": "string"
                },
                "end_date": {
                    "type": "integer"
                },
                "fee": {
                    "type": "number"
                },
                "id": {
                    "type": "string"
                },
                "main_doctor_id": {
                    "type": "string"
                },
                "medical_history_id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "result": {
                    "type": "string"
                },
                "start_date": {
                    "type": "integer"
                },
                "support_doctor_ids": {
                    "description": "List of doctor ids, separated by comma",
                    "type": "string"
                },
                "support_nurse_ids": {
                    "description": "List of nurse ids, separated by comma",
                    "type": "string"
                },
                "updated_at": {
                    "type": "integer"
                },
                "updated_by": {
                    "$ref": "#/definitions/patient.User"
                }
            }
        },
        "patient.Medication": {
            "type": "object",
            "properties": {
                "effects": {
                    "type": "string"
                },
                "expired_date": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "price": {
                    "type": "number"
                },
                "quantity": {
                    "type": "integer"
                }
            }
        },
        "patient.Patient": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "created_at": {
                    "type": "integer"
                },
                "created_by": {
                    "$ref": "#/definitions/patient.User"
                },
                "date_of_birth": {
                    "type": "integer"
                },
                "first_name": {
                    "type": "string"
                },
                "gender": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "phone_number": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "integer"
                },
                "updated_by": {
                    "$ref": "#/definitions/patient.User"
                }
            }
        },
        "patient.PrescriptionMedication": {
            "type": "object",
            "properties": {
                "medication_id": {
                    "type": "string"
                },
                "quantity": {
                    "type": "integer"
                }
            }
        },
        "patient.UpsertMedicalPrescriptionRequest": {
            "type": "object",
            "properties": {
                "medical_history_id": {
                    "type": "string"
                },
                "medications": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/patient.PrescriptionMedication"
                    }
                }
            }
        },
        "patient.UpsertMedicalRecordRequest": {
            "type": "object",
            "properties": {
                "diagnosis": {
                    "type": "string"
                },
                "doctor_notes": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "medical_end_date": {
                    "type": "integer"
                },
                "patient_id": {
                    "type": "string"
                },
                "reason": {
                    "type": "string"
                }
            }
        },
        "patient.UpsertMedicalSurgeryRequest": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "end_date": {
                    "type": "integer"
                },
                "fee": {
                    "type": "number"
                },
                "id": {
                    "type": "string"
                },
                "main_doctor_id": {
                    "type": "string"
                },
                "medical_history_id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "result": {
                    "type": "string"
                },
                "start_date": {
                    "type": "integer"
                },
                "support_doctor_ids": {
                    "description": "List of doctor ids, separated by comma",
                    "type": "string"
                },
                "support_nurse_ids": {
                    "description": "List of nurse ids, separated by comma",
                    "type": "string"
                }
            }
        },
        "patient.UpsertMedicalTreatmentRequest": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "end_date": {
                    "type": "integer"
                },
                "fee": {
                    "type": "number"
                },
                "id": {
                    "type": "string"
                },
                "main_doctor_id": {
                    "type": "string"
                },
                "medical_history_id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "result": {
                    "type": "string"
                },
                "start_date": {
                    "type": "integer"
                },
                "support_doctor_ids": {
                    "description": "List of doctor ids, separated by comma",
                    "type": "string"
                },
                "support_nurse_ids": {
                    "description": "List of nurse ids, separated by comma",
                    "type": "string"
                }
            }
        },
        "patient.UpsertMedicationRequest": {
            "type": "object",
            "properties": {
                "effects": {
                    "type": "string"
                },
                "expired_date": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "price": {
                    "type": "number"
                },
                "quantity": {
                    "type": "integer"
                }
            }
        },
        "patient.UpsertPatientRequest": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "date_of_birth": {
                    "type": "integer"
                },
                "first_name": {
                    "type": "string"
                },
                "gender": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                }
            }
        },
        "patient.User": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "gender": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "phone_number": {
                    "type": "string"
                }
            }
        },
        "patientmodel.GetMedicalHistoryDetailResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "data": {
                    "$ref": "#/definitions/patientmodel.GetMedicalHistoryDetailResponseData"
                }
            }
        },
        "patientmodel.GetMedicalHistoryDetailResponseData": {
            "type": "object",
            "properties": {
                "medical_history": {
                    "$ref": "#/definitions/patient.MedicalHistory"
                },
                "medical_prescriptions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/patient.MedicalPrescription"
                    }
                },
                "medical_surgeries": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/patient.MedicalSurgery"
                    }
                },
                "medical_treatments": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/patient.MedicalTreatment"
                    }
                }
            }
        },
        "patientmodel.GetMedicalHistoryResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "medical_history": {
                    "$ref": "#/definitions/patientmodel.MedicalHistoryData"
                }
            }
        },
        "patientmodel.GetPatientResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "patient": {
                    "$ref": "#/definitions/patient.Patient"
                }
            }
        },
        "patientmodel.ListMedicationResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "data": {
                    "$ref": "#/definitions/patientmodel.ListMedicationResponseData"
                }
            }
        },
        "patientmodel.ListMedicationResponseData": {
            "type": "object",
            "properties": {
                "hasNext": {
                    "type": "boolean"
                },
                "hasPrevious": {
                    "type": "boolean"
                },
                "medications": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/patient.Medication"
                    }
                },
                "page": {
                    "type": "integer"
                },
                "size": {
                    "type": "integer"
                },
                "totalElements": {
                    "description": "Num items in all pages",
                    "type": "integer"
                },
                "totalItems": {
                    "description": "Num items in current page",
                    "type": "integer"
                },
                "totalPages": {
                    "type": "integer"
                }
            }
        },
        "patientmodel.ListPatientResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "data": {
                    "$ref": "#/definitions/patientmodel.ListPatientResponseData"
                }
            }
        },
        "patientmodel.ListPatientResponseData": {
            "type": "object",
            "properties": {
                "hasNext": {
                    "type": "boolean"
                },
                "hasPrevious": {
                    "type": "boolean"
                },
                "page": {
                    "type": "integer"
                },
                "patients": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/patient.Patient"
                    }
                },
                "size": {
                    "type": "integer"
                },
                "totalElements": {
                    "description": "Num items in all pages",
                    "type": "integer"
                },
                "totalItems": {
                    "description": "Num items in current page",
                    "type": "integer"
                },
                "totalPages": {
                    "type": "integer"
                }
            }
        },
        "patientmodel.MedicalHistoryData": {
            "type": "object",
            "properties": {
                "hasNext": {
                    "type": "boolean"
                },
                "hasPrevious": {
                    "type": "boolean"
                },
                "medical_histories": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/patient.MedicalHistory"
                    }
                },
                "page": {
                    "type": "integer"
                },
                "size": {
                    "type": "integer"
                },
                "totalElements": {
                    "description": "Num items in all pages",
                    "type": "integer"
                },
                "totalItems": {
                    "description": "Num items in current page",
                    "type": "integer"
                },
                "totalPages": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
