definitions:
  auth.ChangePasswordRequest:
    properties:
      new_password:
        description: encoded password
        type: string
      old_password:
        description: encoded password
        type: string
      username:
        type: string
    type: object
  auth.CreateEmployeeRequest:
    properties:
      address:
        type: string
      date_of_birth:
        type: integer
      degree_name:
        type: string
      degree_year:
        type: integer
      department_id:
        type: string
      email:
        type: string
      first_name:
        type: string
      gender:
        type: integer
      last_name:
        type: string
      phone_number:
        type: string
      start_date:
        type: integer
      type:
        type: integer
    type: object
  auth.Department:
    properties:
      id:
        type: string
      name:
        type: string
    type: object
  auth.LoginRequest:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  auth.User:
    properties:
      address:
        type: string
      code:
        type: string
      date_of_birth:
        type: integer
      degree_name:
        type: string
      degree_year:
        type: integer
      department:
        $ref: '#/definitions/auth.Department'
      end_date:
        description: Off board date
        type: integer
      first_name:
        type: string
      gender:
        type: integer
      id:
        type: string
      last_name:
        type: string
      phone_number:
        type: string
      start_date:
        description: Onboard date
        type: integer
      state:
        type: integer
      username:
        type: string
    type: object
  authmodel.GenerateLoginSecretRequest:
    properties:
      data:
        type: string
    type: object
  authmodel.GenerateLoginSecretResponse:
    properties:
      code:
        type: string
      data:
        $ref: '#/definitions/authmodel.LoginSecret'
    type: object
  authmodel.LoginResponse:
    properties:
      code:
        type: string
      next_step:
        type: integer
      token:
        type: string
      user:
        $ref: '#/definitions/auth.User'
    type: object
  authmodel.LoginSecret:
    properties:
      secret:
        type: string
    type: object
  basemodel.ApiEmptyResponse:
    properties:
      code:
        type: string
      message:
        type: string
    type: object
  basemodel.ApiError:
    properties:
      code:
        type: string
      details:
        items:
          $ref: '#/definitions/gcommon.ErrorDetail'
        type: array
      message:
        type: string
    type: object
  gcommon.ErrorDetail:
    properties:
      key:
        type: string
      message:
        type: string
    type: object
info:
  contact: {}
paths:
  /auth/change-password:
    post:
      consumes:
      - application/json
      description: Employee Change Password
      parameters:
      - description: Change password Request
        in: body
        name: _
        required: true
        schema:
          $ref: '#/definitions/auth.ChangePasswordRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/basemodel.ApiEmptyResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/basemodel.ApiError'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/basemodel.ApiError'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/basemodel.ApiError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/basemodel.ApiError'
      security:
      - JWT: []
      summary: Employee Change Password
      tags:
      - SA - Auth
  /auth/create-employee:
    post:
      consumes:
      - application/json
      description: Create Employee
      parameters:
      - description: CreateEmployeeRequest Request
        in: body
        name: _
        required: true
        schema:
          $ref: '#/definitions/auth.CreateEmployeeRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/basemodel.ApiEmptyResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/basemodel.ApiError'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/basemodel.ApiError'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/basemodel.ApiError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/basemodel.ApiError'
      security:
      - JWT: []
      summary: Create Employee
      tags:
      - SA - Auth
  /auth/login:
    post:
      consumes:
      - application/json
      description: Employee Login
      parameters:
      - description: Login Request
        in: body
        name: _
        required: true
        schema:
          $ref: '#/definitions/auth.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/authmodel.LoginResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/basemodel.ApiError'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/basemodel.ApiError'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/basemodel.ApiError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/basemodel.ApiError'
      security:
      - JWT: []
      summary: Employee Login
      tags:
      - SA - Auth
  /auth/pre-flight:
    post:
      consumes:
      - application/json
      description: Pre-flight Login
      parameters:
      - description: Request body
        in: body
        name: _
        required: true
        schema:
          $ref: '#/definitions/authmodel.GenerateLoginSecretRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/authmodel.GenerateLoginSecretResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/basemodel.ApiError'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/basemodel.ApiError'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/basemodel.ApiError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/basemodel.ApiError'
      summary: Pre-flight Login
      tags:
      - SA - Auth
swagger: "2.0"
